name: Automated API tests using Postman CLI

on: 
  push:
    branches:
      - main  # Điều chỉnh theo nhánh của bạn, ví dụ main hoặc develop

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Checkout mã nguồn từ repo

      # Cài đặt Postman CLI
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      # Đăng nhập vào Postman CLI
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      # Chạy các API tests với file CSV
      - name: Run API tests
        run: |
          # Chạy Collection 1 với file CSV get_products.csv
          postman collection run "33369205-7e00e67d-9989-4d0e-b63b-fca223c05afe" \
            --environment "33369205-7fcbcbbf-dffe-43b3-9011-aff6170c02c3" \
            --iteration-data "./get_products.csv"

          # Chạy Collection 2 với file CSV forget_password.csv
          postman collection run "33369205-424d911d-9ef1-4719-a01f-b84e94f7d98f" \
            --environment "33369205-7fcbcbbf-dffe-43b3-9011-aff6170c02c3" \
            --iteration-data "./forgot_password.csv"

          # Chạy Collection 3 với file CSV contact_form.csv
          postman collection run "33369205-f73a3642-075c-4b78-b534-ca89a099645a" \
            --environment "33369205-7fcbcbbf-dffe-43b3-9011-aff6170c02c3" \
            --iteration-data "./contact_form.csv"
